# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/artem/cpp_otus/allocator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/artem/cpp_otus/allocator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/local/bin/cpack --config ./CPackSourceConfig.cmake /home/artem/cpp_otus/allocator/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/local/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/cpp_otus/allocator/CMakeFiles /home/artem/cpp_otus/allocator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/artem/cpp_otus/allocator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named allocator_lib

# Build rule for target.
allocator_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 allocator_lib
.PHONY : allocator_lib

# fast build rule for target.
allocator_lib/fast:
	$(MAKE) -f CMakeFiles/allocator_lib.dir/build.make CMakeFiles/allocator_lib.dir/build
.PHONY : allocator_lib/fast

#=============================================================================
# Target rules for targets named test_version

# Build rule for target.
test_version: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_version
.PHONY : test_version

# fast build rule for target.
test_version/fast:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/build
.PHONY : test_version/fast

#=============================================================================
# Target rules for targets named allocator

# Build rule for target.
allocator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 allocator
.PHONY : allocator

# fast build rule for target.
allocator/fast:
	$(MAKE) -f CMakeFiles/allocator.dir/build.make CMakeFiles/allocator.dir/build
.PHONY : allocator/fast

#=============================================================================
# Target rules for targets named math_functions_lib

# Build rule for target.
math_functions_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 math_functions_lib
.PHONY : math_functions_lib

# fast build rule for target.
math_functions_lib/fast:
	$(MAKE) -f CMakeFiles/math_functions_lib.dir/build.make CMakeFiles/math_functions_lib.dir/build
.PHONY : math_functions_lib/fast

#=============================================================================
# Target rules for targets named mylist_lib

# Build rule for target.
mylist_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mylist_lib
.PHONY : mylist_lib

# fast build rule for target.
mylist_lib/fast:
	$(MAKE) -f CMakeFiles/mylist_lib.dir/build.make CMakeFiles/mylist_lib.dir/build
.PHONY : mylist_lib/fast

#=============================================================================
# Target rules for targets named logging_allocator_lib

# Build rule for target.
logging_allocator_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 logging_allocator_lib
.PHONY : logging_allocator_lib

# fast build rule for target.
logging_allocator_lib/fast:
	$(MAKE) -f CMakeFiles/logging_allocator_lib.dir/build.make CMakeFiles/logging_allocator_lib.dir/build
.PHONY : logging_allocator_lib/fast

lib.o: lib.cpp.o

.PHONY : lib.o

# target to build an object file
lib.cpp.o:
	$(MAKE) -f CMakeFiles/allocator_lib.dir/build.make CMakeFiles/allocator_lib.dir/lib.cpp.o
.PHONY : lib.cpp.o

lib.i: lib.cpp.i

.PHONY : lib.i

# target to preprocess a source file
lib.cpp.i:
	$(MAKE) -f CMakeFiles/allocator_lib.dir/build.make CMakeFiles/allocator_lib.dir/lib.cpp.i
.PHONY : lib.cpp.i

lib.s: lib.cpp.s

.PHONY : lib.s

# target to generate assembly for a file
lib.cpp.s:
	$(MAKE) -f CMakeFiles/allocator_lib.dir/build.make CMakeFiles/allocator_lib.dir/lib.cpp.s
.PHONY : lib.cpp.s

logging_allocator.o: logging_allocator.cpp.o

.PHONY : logging_allocator.o

# target to build an object file
logging_allocator.cpp.o:
	$(MAKE) -f CMakeFiles/logging_allocator_lib.dir/build.make CMakeFiles/logging_allocator_lib.dir/logging_allocator.cpp.o
.PHONY : logging_allocator.cpp.o

logging_allocator.i: logging_allocator.cpp.i

.PHONY : logging_allocator.i

# target to preprocess a source file
logging_allocator.cpp.i:
	$(MAKE) -f CMakeFiles/logging_allocator_lib.dir/build.make CMakeFiles/logging_allocator_lib.dir/logging_allocator.cpp.i
.PHONY : logging_allocator.cpp.i

logging_allocator.s: logging_allocator.cpp.s

.PHONY : logging_allocator.s

# target to generate assembly for a file
logging_allocator.cpp.s:
	$(MAKE) -f CMakeFiles/logging_allocator_lib.dir/build.make CMakeFiles/logging_allocator_lib.dir/logging_allocator.cpp.s
.PHONY : logging_allocator.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/allocator.dir/build.make CMakeFiles/allocator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/allocator.dir/build.make CMakeFiles/allocator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/allocator.dir/build.make CMakeFiles/allocator.dir/main.cpp.s
.PHONY : main.cpp.s

math_functions.o: math_functions.cpp.o

.PHONY : math_functions.o

# target to build an object file
math_functions.cpp.o:
	$(MAKE) -f CMakeFiles/math_functions_lib.dir/build.make CMakeFiles/math_functions_lib.dir/math_functions.cpp.o
.PHONY : math_functions.cpp.o

math_functions.i: math_functions.cpp.i

.PHONY : math_functions.i

# target to preprocess a source file
math_functions.cpp.i:
	$(MAKE) -f CMakeFiles/math_functions_lib.dir/build.make CMakeFiles/math_functions_lib.dir/math_functions.cpp.i
.PHONY : math_functions.cpp.i

math_functions.s: math_functions.cpp.s

.PHONY : math_functions.s

# target to generate assembly for a file
math_functions.cpp.s:
	$(MAKE) -f CMakeFiles/math_functions_lib.dir/build.make CMakeFiles/math_functions_lib.dir/math_functions.cpp.s
.PHONY : math_functions.cpp.s

mylist.o: mylist.cpp.o

.PHONY : mylist.o

# target to build an object file
mylist.cpp.o:
	$(MAKE) -f CMakeFiles/mylist_lib.dir/build.make CMakeFiles/mylist_lib.dir/mylist.cpp.o
.PHONY : mylist.cpp.o

mylist.i: mylist.cpp.i

.PHONY : mylist.i

# target to preprocess a source file
mylist.cpp.i:
	$(MAKE) -f CMakeFiles/mylist_lib.dir/build.make CMakeFiles/mylist_lib.dir/mylist.cpp.i
.PHONY : mylist.cpp.i

mylist.s: mylist.cpp.s

.PHONY : mylist.s

# target to generate assembly for a file
mylist.cpp.s:
	$(MAKE) -f CMakeFiles/mylist_lib.dir/build.make CMakeFiles/mylist_lib.dir/mylist.cpp.s
.PHONY : mylist.cpp.s

test_version.o: test_version.cpp.o

.PHONY : test_version.o

# target to build an object file
test_version.cpp.o:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/test_version.cpp.o
.PHONY : test_version.cpp.o

test_version.i: test_version.cpp.i

.PHONY : test_version.i

# target to preprocess a source file
test_version.cpp.i:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/test_version.cpp.i
.PHONY : test_version.cpp.i

test_version.s: test_version.cpp.s

.PHONY : test_version.s

# target to generate assembly for a file
test_version.cpp.s:
	$(MAKE) -f CMakeFiles/test_version.dir/build.make CMakeFiles/test_version.dir/test_version.cpp.s
.PHONY : test_version.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... package_source"
	@echo "... package"
	@echo "... install/strip"
	@echo "... allocator_lib"
	@echo "... test_version"
	@echo "... install/local"
	@echo "... test"
	@echo "... allocator"
	@echo "... rebuild_cache"
	@echo "... math_functions_lib"
	@echo "... mylist_lib"
	@echo "... logging_allocator_lib"
	@echo "... lib.o"
	@echo "... lib.i"
	@echo "... lib.s"
	@echo "... logging_allocator.o"
	@echo "... logging_allocator.i"
	@echo "... logging_allocator.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... math_functions.o"
	@echo "... math_functions.i"
	@echo "... math_functions.s"
	@echo "... mylist.o"
	@echo "... mylist.i"
	@echo "... mylist.s"
	@echo "... test_version.o"
	@echo "... test_version.i"
	@echo "... test_version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

